cert-expiry-finder: Add --with-* k8s options and disable K8S checks by default

diff --git a/cert-expiry-finder b/cert-expiry-finder
--- a/cert-expiry-finder
+++ b/cert-expiry-finder
@@ -8,8 +8,20 @@
 # Usage:
 #
 #     cert-expiry-finder        # lists all certs and days
-#     cert-expiry-finder --min  # lists the soonest expiry
+#     cert-expiry-finder --min  # lists the expiry nearest zero
 #     cert-expiry-finder -h     # shows help and Zabbix example
+#
+# Other options to enable/limit scraping of Kubernetes certificates:
+#
+#     --with(out)-k8s-cert      # (1) certificatemanger.io resources
+#     --with(out)-k8s-ingsecret # (2) tls secrets used by an ingress config
+#     --with(out)-k8s-secret    # (4) tls secrets
+#     --with(out)-all           # enable/disable all optional checks
+#
+# You can set the 'ossobv/vcutil.cert-expiry-finder.includes' label on
+# the 'kube-system' namespace to an (string) value comprised of the
+# bitmasks above. For example "3" for --with-k8s-cert (1) and
+# --with-k8s-ingsecret (2). These then override the command line options.
 #
 # See also:
 #
@@ -18,6 +30,21 @@
 # In some (cron) environments, we might not find all tools (like postconf!).
 # Amend the PATH so we're more likely to.
 PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+
+# Use GNU getopt(1) to reorder arguments
+# Check GNU getopt availability and then use it to reorder arguments and
+# set long options.
+if test "$(getopt -l help -- 'h' 'a b c' -h --help 2>/dev/null)" = "\
+ -h --help -- 'a b c'"; then
+    argv=$(getopt \
+        -l help -l min \
+        -l with-all -l without-all \
+        -l with-k8s-cert -l without-k8s-cert \
+        -l with-k8s-ingsecret -l without-k8s-ingsecret \
+        -l with-k8s-secret -l without-k8s-secret \
+        -- 'h' "$@") || exit 1
+    eval set --"$argv"
+fi
 
 set -u    # skip -e; we do want some results in case of failure
 # set +H  # disable histexpand if you're running the stuff in your shell
@@ -201,60 +228,74 @@ enum_zabbix_certs() {
 }
 
 list_k8s_cert_expiry_days() {
+    local includes="$1"
+
     if ! command -v kubectl >/dev/null; then
         return
     fi
 
-    local name namespace notafter expiry unixtime context
+    local k8s_label='ossobv/vcutil\.cert-expiry-finder\.includes'  # \-escape .
+    local name namespace notafter expiry unixtime context context_includes
     local title=Kubernetes
     kubectl config get-contexts --no-headers -oname |
     while read -r context; do
-        # Get certificate expiry dates from certificates.cert-manager.io
-        kubectl --context="$context" get certificates.cert-manager.io -A \
-            -ojson 2>/dev/null |
-        jq -r '.items[] | select(.status.conditions[0]["status"]=="True" and
-            .status.conditions[0]["reason"]=="Ready") |
-            (.metadata.name + " " + .metadata.namespace + " " +
-            .status.notAfter)' |
-        while read name namespace notafter; do
-            unixtime=$(date --date="$notafter" +%s)
-            expiry=$(((unixtime - global_t0) / 86400))
-            printf '%-7d %s (NS = %s, CRT = %s, CTX = %s)\n' \
-                   $expiry "$title" "$namespace" "$name" "$context"
-        done
+        context_includes=$(
+            kubectl --context="$context" get ns kube-system -o \
+                jsonpath="{.metadata.labels.$k8s_label}")
+        test -n "$context_includes" || context_includes=$includes
+        echo "[[ $context_includes ]]"
 
-        # Get certificate expiry dates from secrets, but only if they
-        # are not annotated with cert-manager.io (because we did those
-        # already)
-        local cert annotations extra tls_used_by_ingress
-        tls_used_by_ingress=$(
-            kubectl --context="$context" get ingress -A -o json |
-            jq -r '.items[]|.metadata.namespace+"."+.spec.tls[]?.secretName' |
-            sort -u)
-        kubectl --context="$context" get secrets -A \
-                --field-selector=type=kubernetes.io/tls -ojson |
-        jq -r '.items[] | (.data["tls.crt"] + " " + .metadata.name + " " +
-               .metadata.namespace + " " +
-               .metadata.annotations["cert-manager.io/issuer-group"])' |
-        while read -r cert name namespace annotations; do
-            if test -n "$annotations"; then
-                :  # has annotation, skip
-            elif ! echo "$tls_used_by_ingress" |
-                    grep -qxF "$namespace.$name"; then
-                # TODO: It would be nice if we did see these in some cases;
-                # these secrets could contain client certs for instance.
-                :  # $namespace.$name not used in any ingress
-            else
-                echo "$cert" | base64 -d | enumerate_x509_expiry_seconds |
-                while read -r expiry extra; do
-                    expiry=$((expiry / 86400))
-                    printf '%-7d %s (NS = %s, CRT = %s, CTX = %s, %s)\n' \
-                        $expiry "$title" "$namespace" "$name" "$context" \
-                        "$extra"
-                done
-            fi
-        done
+        if test "$((context_includes & 1))" -ne 0; then
+            # Get certificate expiry dates from certificates.cert-manager.io
+            kubectl --context="$context" get certificates.cert-manager.io -A \
+                -ojson 2>/dev/null |
+            jq -r '.items[] | select(.status.conditions[0]["status"]=="True"
+                and .status.conditions[0]["reason"]=="Ready") |
+                (.metadata.name + " " + .metadata.namespace + " " +
+                .status.notAfter)' |
+            while read name namespace notafter; do
+                unixtime=$(date --date="$notafter" +%s)
+                expiry=$(((unixtime - global_t0) / 86400))
+                printf '%-7d %s (NS = %s, CRT = %s, CTX = %s)\n' \
+                       $expiry "$title" "$namespace" "$name" "$context"
+            done
+        fi
 
+        if test "$((context_includes & 6))" -ne 0; then
+            # Get certificate expiry dates from secrets, but only if they
+            # are not annotated with cert-manager.io (because we did those
+            # already)
+            local cert annotations extra tls_used_by_ingress
+            tls_used_by_ingress=$(
+                kubectl --context="$context" get ingress -A -o json | jq -r '
+                .items[]|.metadata.namespace+"."+.spec.tls[]?.secretName' |
+                sort -u)
+            kubectl --context="$context" get secrets -A \
+                    --field-selector=type=kubernetes.io/tls -ojson |
+            jq -r '.items[] | (.data["tls.crt"] + " " + .metadata.name + " " +
+                   .metadata.namespace + " " +
+                   .metadata.annotations["cert-manager.io/issuer-group"])' |
+            while read -r cert name namespace annotations; do
+                if test "$((context_includes & 1))" -ne 0 &&
+                        test -n "$annotations"; then
+                    :  # has annotation, skip
+                elif test "$((context_includes & 4))" -eq 0 &&
+                        ! echo "$tls_used_by_ingress" |
+                        grep -qxF "$namespace.$name"; then
+                    # TODO: It would be nice if we did see these in some cases;
+                    # these secrets could contain client certs for instance.
+                    :  # $namespace.$name not used in any ingress
+                else
+                    echo "$cert" | base64 -d | enumerate_x509_expiry_seconds |
+                    while read -r expiry extra; do
+                        expiry=$((expiry / 86400))
+                        printf '%-7d %s (NS = %s, CRT = %s, CTX = %s, %s)\n' \
+                            $expiry "$title" "$namespace" "$name" "$context" \
+                            "$extra"
+                    done
+                fi
+            done
+        fi
     done
 }
 
@@ -348,21 +389,28 @@ expiry_after() {
 }
 
 list_cert_expiry_days() {
+    local includes="$1"
     list_local_cert_expiry_days $(enum_all_certs)
-    list_k8s_cert_expiry_days
+    list_k8s_cert_expiry_days "$includes"
 }
 
+take_negative_value_nearest_zero() {
+    # Instead of the lowest value, we're interested in the value that's
+    # closest to (below) zero.
+    # I.e.: [2,3,4] => 2, [-2,-1,2,3] => -1, [-1, 0, 1] => -1
+    # If you want, you could then ignore values that are very very low
+    # without missing out on values that are now invalid.
+    awk '{
+        if(n==""){n=$1}
+        else if(n>=0&&$1<0){n=$1}
+        else if(n<0&&$1<0&&$1>n){n=$1}
+        else if(n>=0&&$1<n){n=$1}
+    }
+    END{if(n!=""){print n}else{exit 1}}'
+}
 
-if test $# -eq 0; then
-    list_cert_expiry_days
-elif test $# -eq 1 && test "$1" = "--min"; then
-    list_cert_expiry_days |
-        awk '{if(n==""||$1<n){n=$1}}END{if(n!=""){print n}else{exit 1}}'
-elif test $# -eq 1 && test -e "$1"; then
-    list_local_cert_expiry_days "$1"
-    #expiry_after "$1"
-else
-    cat >&2 << __EOF__
+usage() {
+    cat << __EOF__
 Usage: cert-expiry-finder [--min]
 
 Enumerates all X.509 (SSL/TLS) certificates from common known locations
@@ -376,6 +424,52 @@ Zabbix example:
     UserParameter=cert.server.minexpiry,cert-expiry-finder --min || echo 5555
 
 __EOF__
+}
+
+
+OPTIND=0
+INCLUDE=0       # --with-*/--without-*
+SUMMARY=false   # --min
+for arg in "$@"; do
+    case $arg in
+    -h|--help) usage; exit 0;;
+    --min) SUMMARY=true;;
+    --with-k8s-cert) INCLUDE=$((INCLUDE | 1));;
+    --without-k8s-cert) INCLUDE=$((INCLUDE & ~1));;
+    --with-k8s-ingsecret) INCLUDE=$((INCLUDE | 2));;
+    --without-k8s-ingsecret) INCLUDE=$((INCLUDE & ~2));;
+    --with-k8s-secret) INCLUDE=$((INCLUDE | 4));;
+    --without-k8s-secret) INCLUDE=$((INCLUDE & ~4));;
+    --with-all) INCLUDE=255;;
+    --without-all) INCLUDE=0;;
+    --) OPTIND=$((OPTIND+1)); break;;
+    -*) echo "Invalid option $arg; see --help for help" >&2; exit 1;;
+    *) break;;
+    esac
+    OPTIND=$((OPTIND+1))
+done
+shift $OPTIND
+
+
+# Files specified?
+if test $# -gt 0; then
+    if $SUMMARY; then
+        for file in "$@"; do
+            list_local_cert_expiry_days "$file"
+        done | take_negative_value_nearest_zero
+    else
+        for file in "$@"; do
+            list_local_cert_expiry_days "$file"
+        done
+    fi
+    exit 0
+fi
+
+# No files
+if $SUMMARY; then
+    list_cert_expiry_days $INCLUDE | take_negative_value_nearest_zero
+else
+    list_cert_expiry_days $INCLUDE
 fi
 
 # vim: set ts=8 sw=4 sts=4 et ai:
