cert-expiry-finder: Read multiple certs from bundles

diff --git a/cert-expiry-finder b/cert-expiry-finder
--- a/cert-expiry-finder
+++ b/cert-expiry-finder
@@ -171,15 +171,58 @@ enum_zabbix_certs() {
 }
 
 list_cert_expiry_days() {
-    local file expiry
+    local file expiry extra
     for file in "$@"; do
-        expiry=$(expiry_after "$file")
-        if test -n "$expiry"; then
-            expiry=$((expiry / 86400))
-            printf '%-7d %s\n' $expiry "$file"
-        else
-            echo "expiry parse error: $file" >&2
-        fi
+        expiry_after "$file" | while IFS=' ' read -r expiry extra; do
+            if test -n "$expiry"; then
+                expiry=$((expiry / 86400))
+                test -z "$extra" || extra=" $extra"
+                printf '%-7d %s%s\n' $expiry "$file" "$extra"
+            else
+                echo "expiry parse error: $file" >&2
+            fi
+        done
+    done
+}
+
+enumerate_x509_expiry_seconds() {
+    local line date subject
+    foreach_x509 -noout -subject -dates < "$1" | awk '
+        /^subject=/{gsub(/^[^=]*=/, "");subj=$0}
+        /^notAfter=/{gsub(/^[^=]*=/, "");tm=$0;print tm "|" subj;tm=0;subj=""}
+    ' | while IFS='|' read -r date subject; do
+        local unixtime delta
+        unixtime=$(date --date="$date" +%s)
+        delta=$((unixtime - global_t0))
+        echo "$delta ($subject)"
+    done
+}
+
+foreach_x509() {
+    local line
+    umask 0077
+    temp=$(mktemp)
+    trap "rm '$temp'" EXIT
+    awk '
+        /^-----BEGIN CERTIFICATE-----/{buf="";start=1}
+        /^-----END CERTIFICATE-----/{if(start){print buf};start=0}
+        {if(start==2)buf=(buf $0);if(start)start=2}
+    ' | while read -r line; do
+        cat >$temp <<EOF
+-----BEGIN CERTIFICATE-----
+$line
+-----END CERTIFICATE-----
+EOF
+        openssl x509 -in "$temp" "$@"
+    done
+    rm "$temp"
+    trap - EXIT
+}
+
+date_to_unixtime() {
+    local line
+    while read -r line; do
+        date --date="$line" +%s
     done
 }
 
@@ -190,15 +233,13 @@ expiry_after() {
     *.crl|*/crl.pem)
         date=$(openssl crl -in "$file" -noout -nextupdate |
                sed -e '/nextUpdate=/!d;s/.*=//')
+        tn=$(date --date="$date" +%s)
+        echo "$((tn - global_t0))"
         ;;
     *)
-        date=$(openssl x509 -in "$file" -noout -dates |
-               sed -e '/notAfter=/!d;s/.*=//')
+        enumerate_x509_expiry_seconds "$file"
         ;;
     esac
-    tn=$(date --date="$date" +%s)
-    td=$((tn - global_t0))
-    echo $td
 }
 
 if test $# -eq 0; then
@@ -206,6 +247,9 @@ if test $# -eq 0; then
 elif test $# -eq 1 && test "$1" = "--min"; then
     list_cert_expiry_days $(enum_all_certs) |
     awk '{if(n==""||$1<n){n=$1}}END{if(n!=""){print n}else{exit 1}}'
+elif test $# -eq 1 && test -e "$1"; then
+    list_cert_expiry_days "$1"
+    #expiry_after "$1"
 else
     cat >&2 << __EOF__
 Usage: cert-expiry-finder [--min]
