efibootmirrorsetup: Allow user to continue on disks with different partitions

diff --git a/efibootmirrorsetup b/efibootmirrorsetup
--- a/efibootmirrorsetup
+++ b/efibootmirrorsetup
@@ -55,6 +55,18 @@ check_args() {
 }
 
 check_two_disk_args() {
+    # Example pre-condition:
+    #   $disk0      = $1 = "/dev/sda"
+    #   $disk1      = $2 = "/dev/sdb"
+    # Example post-condition:
+    #   # (sorted by $diskbyid0 < $diskbyid1)
+    #   $disk0      = "sdb"
+    #   $diskbyid0  = "/dev/disk/by-id/ata-INTEL_SSDSC2KB019T8_PHYF83"
+    #   $disk1      = "sda"
+    #   $diskbyid1  = "/dev/disk/by-id/ata-INTEL_SSDSC2KB019T8_PHYF84"
+    #   $partitions = "1 524288 <LF> 2 1874848071"  # num size <LF> num size
+    local partitions0
+    local partitions1
     disk0="${1:-}"
     disk1="${2:-}"
     if ! test -b "$disk0" || ! test -b "$disk1"; then
@@ -84,9 +96,16 @@ check_two_disk_args() {
         /proc/partitions | sort -n)
     if test -z "$partitions0" || test "$partitions0" != "$partitions1"; then
         echo "Partition mismatch, expected equality:" >&2
-        echo "$disk0: $partitions0" >&2
-        echo "$disk1: $partitions1" >&2
-        exit 1
+        printf "  /dev/$disk0p%s %s\\n" $partitions0 >&2
+        echo "versus:" >&2
+        printf "  /dev/$disk1p%s %s\\n" $partitions1 >&2
+        echo >&2
+        echo -n "Is this the right disk? Continue anyway [y/N]? "
+        read yn
+        if test "$yn" != y; then
+            echo "Aborted" >&2
+            exit 1
+        fi
     fi
     partitions="$partitions0"
 }
@@ -196,7 +215,15 @@ check_two_efi_partitions() {
     part1=$(echo "$located1" | cut -d' ' -f2)
     uuid0=$(echo "$located0" | cut -d' ' -f3)
     uuid1=$(echo "$located1" | cut -d' ' -f3)
-    test -n "$part0" && test "$part0" = "$part1"
+    test -n "$part0" && test -n "$part1"
+    if test "$part0" != "$part1"; then
+        # NOTE: This may very well work, but we'll want to test this
+        # before allowing it.
+        echo "Did not expect EFI on different partition numbers ($disk0$part0 \
+vs $disk1$part1)" >&2
+        exit 1
+    fi
+
     if test -z "$uuid0" || test "$uuid0" = "$uuid1"; then
         echo "Empty or duplicate PARTUUID=" >&2
         echo "Please fix with fdisk: p x i/u r w" >&2
@@ -245,10 +272,17 @@ make_grub_postinstall() {
     dst=/etc/kernel/postinst.d/zz-grub-install-efibootmirrorsetup
     cat >"$temp" <<EOF2
 #!/bin/sh
+# THIS FILE IS GENERATED BY efibootmirrorsetup (ossobv/vcutil)
+
+disk0='$diskbyid0'
+disk0name="\${disk0##*/}"  # ${diskbyid0##*/}
+disk0part=$part0
+disk1='$diskbyid1'
+disk1name="\${disk1##*/}"  # ${diskbyid1##*/}
+disk1part=$part1
+
 # Do not use grub-install --bootloader-id because it breaks the hardcoded path
 # in grub.efi to EFI\\\\ubuntu\\\\grub.cfg
-disk0=$diskbyid0
-disk1=$diskbyid1
 err=
 grub-install --efi-directory /boot/efi \$disk0 || err=1
 grub-install --efi-directory /boot/efi2 \$disk1 || err=1
@@ -282,11 +316,8 @@ for label in ubuntu \$(basename \$disk0) \$(basename \$disk1); do
     done
 done
 
-part=$part0  # partition $part0 == $part1
-for disk in \$disk0 \$disk1; do
-    label=\$(basename "\$disk")
-    efibootmgr -q -c -d \$disk -p \$part -w -L "\$label" -l "\$binpath"
-done
+efibootmgr -q -c -d \$disk0 -p \$disk0part -w -L "\$disk0name" -l "\$binpath"
+efibootmgr -q -c -d \$disk1 -p \$disk1part -w -L "\$disk1name" -l "\$binpath"
 EOF2
     if ! cmp -s "$dst" "$temp"; then
         diff --text -Nu "$dst" "$temp" || true
