efibootmirrorsetup: Always create FAT16 partitions for EFI
Creating a FAT16 partition for EFI is almost always the right thing to
do. FAT32 works too, but only if the cluster count is high enough.
mkfs.vat did it's calculation wrong and produced with a low number if
sectors were not 512 bytes. Fixed in dosfstools 4.2:

      * fs size >   32G:  32k clusters
    - *
    - * This only works correctly for 512 byte sectors!
      */
    -uint32_t sz_mb = info->size / (1024 * 1024);
    -cluster_size =
    -    sz_mb > 32 * 1024 ? 64 : sz_mb > 16 * 1024 ? 32 : sz_mb >
    -    8 * 1024 ? 16 : sz_mb > 260 ? 8 : 1;
    +unsigned long long int sectors = info->size / sector_size;
    +cluster_size = sectors > 32*1024*1024*2 ? 64 :
    +               sectors > 16*1024*1024*2 ? 32 :
    +               sectors >  8*1024*1024*2 ? 16 :
    +               sectors >     260*1024*2 ? 8 : 1;

Rules of thumb:

- for disks between 2MiB and 2GiB, FAT16 is fine;
- for disks above 1GiB where you want a smallish cluster size, consider
  FAT32.

Sample values for FAT16:

-  512 bytes/sector,  1 sectors/cluster:  4085* 512*1 =   2MiB (min for 512)
- 4096 bytes/sector,  1 sectors/cluster:  4085*4096*1 =  16MiB (min for 4096)
-  512 bytes/sector,  8 sectors/cluster: 65524* 512*8 = 255MiB (sane for 512)
- 4096 bytes/sector,  2 sectors/cluster: 65524*4096*2 = 511MiB (sane for 4096)
-  512 bytes/sector, 64 sectors/cluster: 65524* 512*1 =   2GiB (max for 512)
- 4096 bytes/sector, 64 sectors/cluster: 65524*4096*1 =  16GiB (max for 4096)

(Yes, we realize 128 sectors/cluster is legit, but non-standard. Avoid
problems.)

diff --git a/efibootmirrorsetup b/efibootmirrorsetup
--- a/efibootmirrorsetup
+++ b/efibootmirrorsetup
@@ -15,15 +15,15 @@
 # Supply /dev/disk and /dev/otherdisk.
 #
 # It will do the following, if it hasn't been done yet:
-# - ensure there is a FAT32 fs on the other disks EFI partition
+# - ensure there is a FAT filesystem on the other drive's EFI partition
 # - ask if it can update fstab for you (you'll get to see a diff)
 # - mount the EFI partitions on /boot/efi and /boot/efi2
 # - ask if it may add/update zz-grub-install-efibootmirrorsetup in the
 #   /etc/kernel/postinst.d/ update hooks
 # - run that hook, inserting both partitions into the EFI boot order
 #
-# NOTE: If the partition IDs are equal on the different disks (maybe you
-# cloned the disks), it will prompt you to manually fix that.
+# NOTE: If the partition IDs are equal on the different drives (maybe you
+# cloned the drives), it will prompt you to manually fix that.
 #
 # The script is idempotent, so running it multiple times should be safe.
 #
@@ -38,7 +38,7 @@
 #     HD(<N>,GPT,<PARTUUID>,0x800,0x100000)/File(\EFI\UBUNTU\SHIMX64.EFI)
 #
 # The DISK_MODEL_NAME and PARTUUID speak for themselves (see blkid). The
-# N is the Nth partition on the disk (2 for sda2). The File() path may
+# N is the Nth partition on the drive (2 for sda2). The File() path may
 # be different, for starters depending on whether secure boot is
 # enabled or not.
 #
@@ -104,7 +104,7 @@ check_two_disk_args() {
         echo "versus:" >&2
         printf "  /dev/$disk1p%s %s\\n" $partitions1 >&2
         echo >&2
-        echo -n "Is this the right disk? Proceed anyway [y/N]? "
+        echo -n "Is this the right drive? Proceed anyway [y/N]? "
         read yn
         if test "$yn" != y; then
             echo "Aborted" >&2
@@ -258,7 +258,7 @@ check_two_efi_partitions() {
         exit 1
     elif test $located_n -gt 1 &&
             test $(echo "$located"|cut -d' ' -f1|sort -u| wc -l) -eq 1; then
-        echo "Did not expect more VFAT partitions on same disk. Abort" >&2
+        echo "Did not expect more VFAT partitions on same drive. Abort" >&2
         exit 1
     fi
 
@@ -287,7 +287,17 @@ check_two_efi_partitions() {
             echo "Aborted" >&2
             exit 1
         fi
-        mkfs -t vfat -F 32 -n EFI $destpart
+        # Until this commit, the sectors/cluster default for FAT32 is wrong:
+        # https://github.com/dosfstools/dosfstools/pull/153/commits/
+        #   404ead8adb76fcb3a3521c0c3f13ef39898c0818
+        # For a 510MiB filesystem, we'd get 130300 clusters for 512 byte
+        # sectors (4K clusters), but only 16312 clusters for 4096 byte
+        # sectors (32K clusters(!)). Microsoft and UEFI systems will detect
+        # FAT16 if there are fewer than 65,525 clusters.
+        # Two options, use FAT16, or manually reduce the number of sectors
+        # per cluster to 1 (using -s 1), but that is only valid if the
+        # sectors are large enough (4096).
+        mkfs -t vfat -F 16 -n EFI $destpart
 
         located="$(locate_efi_partitions)"
         located_n=$(lines "$located")
