ipmikvm: Consolidate ipmikvm-tls2020 and ipmikvm into ipmikvm

diff --git a/ipmikvm b/ipmikvm
--- a/ipmikvm
+++ b/ipmikvm
@@ -1,145 +1,178 @@
 #!/bin/sh
 # ipmikvm (part of ossobv/vcutil) // wdoekes/2019-2020 // Public Domain
 #
-# A wrapper to call the IPMIView KVM console without starting IPMIView
-# (and avoiding a bug that attempts to connect to port 0).
+# A wrapper to call the SuperMicro iKVM console bypassing Java browser
+# plugins.
 #
-# Requirements:
-# - ipmiview installed in /opt/ipmiview
-# - curl (for 2-step user/pass)
-# - socat (for TLS-tunnel)
+# Requirements: base64, curl, java
 #
 # Usage:
 #
 #   $ ipmikvm
-#   Usage: ./ipmikvm [-u ADMIN] [-P ADMIN] [-p 5900] IP.ADD.RE.SS
-#   Options: [-k (nossl)] [-2 (2-step user/pass fetch)]
+#   Usage: ipmikvm [-u ADMIN] [-P ADMIN] IP.ADD.RE.SS
 #
 #   $ ipmikvm 10.11.12.13 -P otherpassword
 #   (connects KVM console on IPMI device at 10.11.12.13)
 #
-# This has been tested with IPMIView 2.16.0+build190528 (and
-# specifically, the tw.com.aten.ikvm.KVMMain 1.69+r14 (or 1.69.20)).
+# This has been tested with:
+# - iKVM__V1.69.19.0x0
+# - iKVM__V1.69.22.0x0
+# - iKVM__V1.69.24.0x0
+# - iKVM__V1.69.25.0x0
+# - iKVM__V1.69.39.0x0
 #
-# See also: ipmikvm-tls2020
+# See also: ipmikvm
 #
-set -eu
-ipmipath=/opt/ipmiview
+test -z "$HOME" && echo 'missing $HOME' && exit 1
+set -u
+APP_CACHE_DIR="$HOME/.local/lib/ipmikvm"
 
-host=
-user=ADMIN
-pass=ADMIN
-port=5900
-step2=
-tls=1
-vm=0  # ???
+IP=
+USER=ADMIN
+PASS=ADMIN
 
 # Use getopt(1) to reorder arguments
 eval set --"$(getopt -- 'hk2p:u:P:' "$@")"
 
 usage() {
     test ${1:-1} -ne 0 && exec >&2  # non-zero? write to stderr
-    echo "Usage: $0 [-u ADMIN] [-P ADMIN] [-p 5900] IP.ADD.RE.SS"
-    echo "Options: [-k (nossl)] [-2 (2-step user/pass fetch)]"
+    echo "Usage: $0 [-u ADMIN] [-P ADMIN] IP.ADD.RE.SS"
     exit ${1:-1}
 }
 
-while getopts 'hk2p:u:P:' OPTION; do
+while getopts 'hu:P:' OPTION; do
     case "$OPTION" in
     h) usage 0;;
-    k) tls=0;;
-    p) port=$OPTARG;;
-    u) user=$OPTARG;;
-    P) pass=$OPTARG;;
-    2) step2=1;;
+    u) USER=$OPTARG;;
+    P) PASS=$OPTARG;;
     ?) usage 1;;
     esac
 done
 shift $((OPTIND - 1))
 
 test $# -ne 1 && usage
-host=${1:-}; shift
-test -z "$host" && usage
+IP=${1:-}; shift
+test -z "$IP" && usage
 
-# Try ping first
-if ! ping -q -c1 -w2 "$host" >/dev/null; then
-    echo "No ping response from $host" >&2
-    exit 1
-fi
 
-# SuperMicro 2-step auth request (get user+pass from jnlp download)
-if test -n "$step2"; then
-    set +e
+get_launch_jnlp() {
+    management_ip="$1"
+    user="$2"
+    pass="$3"
+
     fail=1
-    url="https://$host"
+    url="https://$management_ip"
     temp=$(mktemp)
-    b64_user=$(echo -n "$user" | base64 -w0 | sed -e 's/=/%3D/g;s/+/%2B/g')
-    b64_pass=$(echo -n "$pass" | base64 -w0 | sed -e 's/=/%3D/g;s/+/%2B/g')
-    if curl --fail -sk --cookie-jar "$temp" -XPOST "$url/cgi/login.cgi" \
-          --data "name=$b64_user&pwd=$b64_pass&check=00" -o/dev/null; then
-        out=$(curl --fail -sk --cookie "$temp" \
-            "$url/cgi/url_redirect.cgi?url_name=man_ikvm&url_type=jwsk")
-        if test $? -eq 0; then
-            user_pass=$(
-              echo "$out" | grep -FA2 "<argument>$host</argument>" |
-                sed -e '1d;s/^[[:blank:]]*<argument>//;s/<\/argument>.*//' |
-                tr '\n' ' ' | sed -e 's/ *$//')
-            user=${user_pass% *}
-            pass=${user_pass#* }
-            fail=
+    data=$(curl --fail -Lks --cookie-jar "$temp" "$url")
+    if test $? -ne 0 || ! echo "$data" | grep -q '<form '; then
+        echo "unexpected login page: $data" >&2
+        data=
+    elif echo "$data" | grep -q '=.*btoa'; then
+        user=$(echo -n "$user" | base64 -w0 | sed -e 's/=/%3D/g;s/+/%2B/g')
+        pass=$(echo -n "$pass" | base64 -w0 | sed -e 's/=/%3D/g;s/+/%2B/g')
+    fi
+    data=$(test -n "$data" &&
+      curl --fail -Lks --cookie "$temp" --cookie-jar "$temp" \
+        -XPOST "$url/cgi/login.cgi" --data "name=$user&pwd=$pass&check=00")
+    if test $? -ne 0 || ! echo "$data" | grep -qF 'url_name=mainmenu'; then
+        echo "unexpected post-login page: $data" >&2
+    elif test -n "$user"; then
+        for url_name in man_ikvm ikvm; do
+            data=$(curl --fail -Lks --cookie "$temp" \
+                -H "Referer: $url/cgi/url_redirect.cgi?url_name=man_ikvm" \
+                "$url/cgi/url_redirect.cgi?url_name=$url_name&url_type=jwsk")
+            test $? -ne 0 && echo "$data" | grep -q '^<jnlp spec=' && break
+        done
+        if ! echo "$data" | grep -q '^<jnlp spec='; then
+            echo "unexpected jnlp page: $data" >&2
+            data=
         fi
     fi
     rm "$temp"
-    if test -n "$fail" || test -z "$user" || test -z "$pass"; then
-        echo "Problem getting password from web interface" >&2
-        exit 1
+    test -n "$data" && echo "$data"
+}
+# SYNOPSIS: get_launch_jnlp 10.x.x.x USERNAME PASSWORD
+
+get_ikvm_jar() {
+    launch_jnlp="$1"
+    app_cache_dir="$2"
+
+    jar=$(get_jar "$launch_jnlp")
+    if test -z "$jar"; then
+        echo "cannot find jar name in jnlp: $launch_jnlp" >&2
     fi
+    jar_base=$(basename "$jar") # iKVM__V1.69.31.0x0.jar
+    jar_base=${jar_base%.jar}   # iKVM__V1.69.31.0x0
+    app_cache_dir="$app_cache_dir/$jar_base"
+    test -d "$app_cache_dir" || mkdir -p "$app_cache_dir" || exit 1
+    if ! test -f "$app_cache_dir/$jar"; then
+        install_ikvm_application "$launch_jnlp" "$app_cache_dir" >&2 || exit 1
+        test -f "$app_cache_dir/$jar" || exit 1
+    fi
+    echo "$app_cache_dir/$jar"
+}
+# SYNOPSIS: get_ikvm_jar JNLP_DATA APP_CACHE_DIR
+
+get_jar() {
+    echo "$1" | sed -e '
+      /<jar /!d
+      s#.* href="\([^"]*\).jar".*version="\([^"]*\)".*#\1__V\2.jar#
+      s#.* href="\([^"]*\).jar".*#\1.jar#'
+}
+# SYNOPSIS: get_jar JNLP_DATA
+
+get_arguments() {
+    echo "$1" |
+      sed -e '/<argument>/!d;s#.*<argument>\([^<]*\)</argument>.*#\1#' |
+      sed -e 's/^$/./g'  # empty args would be skipped..
+}
+# SYNOPSIS: get_arguments JNLP_DATA  # returns LF-separated args
+
+exec_ikvm() {
+    jar="$1"; shift
+    exec java -Djava.library.path="$(dirname "$jar")" \
+      -cp "$jar" tw.com.aten.ikvm.KVMMain "$@"
+}
+# SYNOPSIS: exec_ikvm 10.x.x.x KVM_USERNAME KVM_PASSWORD
+
+install_ikvm_application() {
+    launch_jnlp="$1"
+    destdir="$2"
+
     set -e
-fi
+    codebase=$(
+      echo "$launch_jnlp" | sed -e '/<jnlp /!d;s/.* codebase="//;s/".*//')
+    jar=$(get_jar "$launch_jnlp")
+    linuxlibs=$(
+      echo "$launch_jnlp" | sed -e '
+        /<nativelib.*linux.*x86_64/!d
+        s#.* href="\([^"]*\).jar".*version="\([^"]*\)".*#\1__V\2.jar#
+        s#.* href="\([^"]*\).jar".*#\1.jar#' | sort -u)
+    set -x
+    mkdir -p "$destdir"
+    cd "$destdir"
+    for x in $jar $linuxlibs; do
+        if curl -ko "$x.pack.gz" "$codebase$x.pack.gz"; then
+            unpack200 "$x.pack.gz" "$x"
+        elif curl -ko "$x" "$codebase$x"; then
+            :
+        else
+            echo "$launch_jnlp"
+            false
+        fi
+    done
+    unzip -o liblinux*.jar
+    rm -rf META-INF
+    set +x
+    set +e
+}
+# SYNOPSIS: install_ikvm_application JNLP_DATA DESTDIR
 
-# Check whether it speaks TLS, and auto-disable if not
-if test $tls -ne 0 &&
-        ! openssl s_client -connect "$host:$port" -quiet -state \
-          </dev/null 2>&1 | grep -q ^SSL.*read; then
-    echo "No TLS/SSL detected. Trying without instead" >&2
-    tls=0
-fi
 
-# TLS wrapping
-if test $tls -ne 0; then
-    remotehost=$host
-    remoteport=$port
-    host=127.0.0.1
-    port=$((30000 + ($$ % 10000)))  # use this-pid as "random"
-    echo "Spawning TLS/SSL socat $host:$port -> $remotehost:$remoteport..." >&2
-    # spawn socat
-    crtpath="$ipmipath/BMCSecurity" # "/opt/ipmiview/BMCSecurity/client.crt"
-    crtopt="commonname=IPMI,cafile=$crtpath/server.crt"
-    crtopt="$crtopt,cert=$crtpath/client.crt,key=$crtpath/client.key"
-    socat "TCP4-LISTEN:$port" "OPENSSL:$remotehost:$remoteport,$crtopt" &
-    tlspid=$!
-    # socat doesn't connect until we connect, so we don't need to sleep
-fi
+JNLP=$(get_launch_jnlp "$IP" "$USER" "$PASS")
+test -z "$JNLP" && echo "Failed to get launch.jnlp" >&2 && exit 1
 
-# Yes. Passing usernames and passwords on the command line is insecure.
-# You can pass them through a file if you want:
-# printf 'ID: ADMIN\nPassword: ADMIN\nPort: 5900\nVm: 0\n' >IP.ADD.RE.SS.temp
-# But I don't think your desktop/laptop is going to be insecure enough
-# to warrant that. (And in that case, this script needs to get the user/pass
-# through a different means as well :P)
+JAR=$(get_ikvm_jar "$JNLP" "$APP_CACHE_DIR")
+test -z "$JAR" && echo "Failed to get iKVM*.jar" >&2 && exit 1
 
-echo "Attempting iKVM connection to $host:$port..." >&2
-ret=0
-"$ipmipath/jre/bin/java" -Djava.library.path="$ipmipath" \
-    -jar "$ipmipath/iKVM.jar" "$host" "$user" "$pass" "$vm" "$port" || ret=$?
-echo "(iKVM exit code $ret)" >&2
-
-# TLS, clean up socat
-if test $tls -ne 0; then
-    if kill $tlspid 2>/dev/null; then
-        sleep 1
-        kill -0 $tlspid 2>/dev/null && kill -9 $tlspid
-    fi
-fi
-
-exit $ret
+exec_ikvm "$JAR" $(get_arguments "$JNLP")
