ipmikvm: Some refactoring, replacing globals with locals where possible

diff --git a/ipmikvm b/ipmikvm
--- a/ipmikvm
+++ b/ipmikvm
@@ -98,20 +98,20 @@ test -n "$PASS" && PASSES="$PASS "; PASS=
 
 
 get_launch_jnlp() {
-    management_ip="$1"
-    users="$2"
-    passes="$3"
+    local management_ip="$1"
+    local users="$2"
+    local passes="$3"
 
-    url="https://$management_ip"
-    local_append=''
-    temp=$(mktemp)
+    local url="https://$management_ip"
+    local local_append=''
+    local temp=$(mktemp)
 
     until test -z "$users"; do
-        user=${users%% *}; users=${users#* }
-        pass=${passes%% *}; passes=${passes#* }
+        local user=${users%% *}; users=${users#* }
+        local pass=${passes%% *}; passes=${passes#* }
         echo "attempting login on '$management_ip' with user $user" >&2
 
-        data=$(curl --fail -LksS --cookie-jar "$temp" "$url")
+        local data="$(curl --fail -LksS --cookie-jar "$temp" "$url")"
         if test $? -ne 0 || ! echo "$data" | grep -q '<form '; then
             echo "unexpected login page on address '$management_ip': $data" >&2
             data=
@@ -130,7 +130,7 @@ get_launch_jnlp() {
                 break
             fi
         fi
-        use_base64=$(echo "$data" | grep -q '=.*btoa' && echo 1)
+        local use_base64=$(echo "$data" | grep -q '=.*btoa' && echo 1)
 
         if test -n "$use_base64"; then
             user=$(echo -n "$user" | base64 -w0 | sed -e 's/=/%3D/g;s/+/%2B/g')
@@ -139,10 +139,10 @@ get_launch_jnlp() {
         data=$(test -n "$data" &&
           curl --fail -LksS --cookie "$temp" --cookie-jar "$temp" \
             -XPOST "$url/cgi/login.cgi" --data "name=$user&pwd=$pass&check=00")
-        ret=$?
-        fail_heur=0
+        local ret=$?
+        local fail_heur=0
         if test $ret -eq 0; then
-            ok_heur=$(echo "$data" |
+            local ok_heur=$(echo "$data" |
                 grep -cF 'url_redirect.cgi?url_name=mainmenu')
             fail_heur=$(echo "$data" | grep -ciE \
                 "url_redirect[.]cgi[?]url_name=login_alert|alert[(]|\
@@ -179,39 +179,47 @@ get_launch_jnlp() {
 }
 # SYNOPSIS: get_launch_jnlp 10.x.x.x USERNAME PASSWORD
 
-get_ikvm_jar() {
-    launch_jnlp="$1"
-    app_cache_dir="$2"
+get_app_jar() {
+    local launch_jnlp="$1"
+    local app_cache_dir="$2"
 
-    jar=$(get_jar "$launch_jnlp")
-    if test -z "$jar"; then
-        echo "cannot find jar name in jnlp: $launch_jnlp" >&2
+    local app_jar="$(get_jars "$launch_jnlp" | head -n1)"  # first jar
+    if test -z "$app_jar"; then
+        echo "cannot find application jar name in jnlp: $launch_jnlp" >&2
+        exit 1
     fi
-    jar_base=$(basename "$jar") # iKVM__V1.69.31.0x0.jar
-    jar_base=${jar_base%.jar}   # iKVM__V1.69.31.0x0
-    app_cache_dir="$app_cache_dir/$jar_base"
+    local jar_base="$(basename "$app_jar")" # iKVM__V1.69.31.0x0.jar
+    local jar_base="${jar_base%.jar}"   # iKVM__V1.69.31.0x0
+    local app_cache_dir="$app_cache_dir/$jar_base"
+    umask 0077  # storing latest.jnlp here; might contain temp passwords
     test -d "$app_cache_dir" || mkdir -p "$app_cache_dir" || exit 1
-    if ! test -f "$app_cache_dir/$jar"; then
+    echo "$launch_jnlp" >"$app_cache_dir/latest.jnlp"
+    if ! test -f "$app_cache_dir/$app_jar"; then
         install_ikvm_application "$launch_jnlp" "$app_cache_dir" >&2 || exit 1
-        test -f "$app_cache_dir/$jar" || exit 1
+        test -f "$app_cache_dir/$app_jar" || exit 1
     fi
-    echo "$app_cache_dir/$jar"
+    echo "$app_cache_dir/$app_jar"
 }
-# SYNOPSIS: get_ikvm_jar JNLP_DATA APP_CACHE_DIR
+# SYNOPSIS: get_app_jar JNLP_DATA APP_CACHE_DIR
 
-get_jar() {
+get_app_class() {
+    echo "$1" | sed -ne 's/.*<application-desc .*main-class="\([^"]*\)".*/\1/p'
+}
+# SYNOPSIS: get_app_class JNLP_DATA
+
+get_jars() {
     echo "$1" | sed -e '
       /<jar /!d
       s#.* href="\([^"]*\).jar".*version="\([^"]*\)".*#\1__V\2.jar#
       s#.* href="\([^"]*\).jar".*#\1.jar#'
 }
-# SYNOPSIS: get_jar JNLP_DATA
+# SYNOPSIS: get_jars JNLP_DATA
 
 get_arguments() {
-    certarg=$(echo "$1" | tr '\n' '|' | sed -e '
+    local certarg="$(echo "$1" | tr '\n' '|' | sed -e '
       /-----BEGIN CERTIFICATE/!d
       s/.*<argument>\(-----BEGIN CERTIFICATE[^<]*\)<.*/\1/
-      '"s/['\"$]//g"';s/|/${LF}/g')
+      '"s/['\"$]//g"';s/|/${LF}/g')"
     echo "$1" |
       sed -e '/<argument>/!d;s#.*<argument>\([^<]*\)</argument>.*#\1#' |
       sed -e "s/['\"$]//g;s/.*/'&'/" |
@@ -224,38 +232,46 @@ get_arguments() {
 #   ${LF} variable is added, so we get a linefeed in the eval.
 # USAGE: LF=$'\n'; eval set -- $(get_arguments "$JNLP_DATA")
 
-exec_ikvm() {
-    jar="$1"; shift
-    case $jar in
+exec_app() {
+    local jar="$1"; shift
+    local class="$1"; shift
+    if test -z "$class"; then
+	class=$(unzip -c "$jar" META-INF/MANIFEST.MF |
+	    awk '/^Main-Class[[:blank:]]*:/{print $2}' |
+	    sed -e 's/[[:cntrl:][:space:]]//g')
+	echo "found Main-Class $class in $jar" >&2
+    fi
     # iKVM
-    */iKVM*.jar) class=tw.com.aten.ikvm.KVMMain;;
+    #*/iKVM*.jar) class=tw.com.aten.ikvm.KVMMain;;
     # Redirection Viewer v1.46
-    */JViewer.jar) class=com.ami.kvm.jviewer.JViewer;;
-    *) echo "Unknown entrypoint in $jar" >&2; exit 1;;
-    esac
-    exec java -Djava.library.path="$(dirname "$jar")" \
-      -cp "$jar" $class "$@"
+    #*/JViewer.jar) class=com.ami.kvm.jviewer.JViewer;;
+    if test -z "$class"; then
+	echo "Unknown entrypoint in $jar" >&2
+	exit 1
+    fi
+    set -x
+    exec java -Djava.library.path="${jar%/*}" -cp "$jar" "$class" "$@"
 }
-# SYNOPSIS: exec_ikvm 10.x.x.x KVM_USERNAME KVM_PASSWORD
+# SYNOPSIS: exec_app JAR CLASS 10.x.x.x KVM_USERNAME KVM_PASSWORD
 
 install_ikvm_application() {
-    launch_jnlp="$1"
-    destdir="$2"
+    local launch_jnlp="$1"
+    local destdir="$2"
 
     set -e
-    codebase=$(
+    local codebase=$(
       echo "$launch_jnlp" | sed -e '/<jnlp /!d;s/.* codebase="//;s/".*//')
     if echo "$launch_jnlp" | grep -q DISABLED_SSL; then
         codebase=$(as_http "$codebase")
     fi
     test "${codebase%/}" = "$codebase" || codebase="${codebase%/}"
-    jar=$(get_jar "$launch_jnlp")
+    local jars="$(get_jars "$launch_jnlp")"
     case "$(uname -s)" in
-        Linux) libprefix=liblinux;;
-        Darwin) libprefix=libmac;;
+        Linux) local libprefix=liblinux;;
+        Darwin) local libprefix=libmac;;
         *) echo "Unknown platform: $(uname -s)" >&2; exit 1;;
     esac
-    nativelibs=$(
+    local nativelibs=$(
       echo "$launch_jnlp" | sed -e '
         /<nativelib.*'$libprefix'.*x86_64/!d
         s#.* href="\([^"]*\).jar".*version="\([^"]*\)".*#\1__V\2.jar#
@@ -263,12 +279,18 @@ install_ikvm_application() {
     set -x
     mkdir -p "$destdir"
     cd "$destdir"
-    for x in $jar $nativelibs; do
+    for x in $jars $nativelibs; do
         test "${x%/*}" = "$x" || mkdir -p "${x%/*}"
-        if curl --fail -ko "$x.pack.gz" "$codebase/$x.pack.gz"; then
-            unpack200 "$x.pack.gz" "$x"
-        elif curl --fail -ko "$x" "$codebase/$x"; then
+        if curl -sS --fail -ko "$x" "$codebase/$x" &&
+		file --brief --mime "$x" |
+		grep -E '^application/(java-archive|zip)'; then
             :
+        elif curl -sS --fail -ko "$x.pack.gz" "$codebase/$x.pack.gz" &&
+		file --brief --mime "$x.pack.gz" |
+		grep -E '^application/gzip' &&
+		gunzip "$x.pack.gz" &&
+		unpack200 "$x.pack" "$x"; then
+	    :
         else
             echo "$launch_jnlp"
             false
@@ -289,12 +311,13 @@ else
     test -z "$JNLP" && echo "Failed to get launch.jnlp" >&2 && exit 1
 fi
 
-JAR=$(get_ikvm_jar "$JNLP" "$APP_CACHE_DIR")
-test -z "$JAR" && echo "Failed to get iKVM*.jar" >&2 && exit 1
+JAR=$(get_app_jar "$JNLP" "$APP_CACHE_DIR")
+test -z "$JAR" && echo "Failed to get iKVM*.jar/JViewer*.jar" >&2 && exit 1
+CLASS=$(get_app_class "$JNLP")  # might be blank
 
 # Load quoted arguments (including multiline args)
 LF='
 '
 eval set -- $(get_arguments "$JNLP")
 
-exec_ikvm "$JAR" "$@"
+exec_app "$JAR" "$CLASS" "$@"
