kubectl-sh-secret: Improve internals, add set -e and set -u

diff --git a/kubectl-sh-secret b/kubectl-sh-secret
--- a/kubectl-sh-secret
+++ b/kubectl-sh-secret
@@ -1,5 +1,6 @@
 #!/bin/bash
-# kubectl-sh-secret (part of ossobv/vcutil) // wdoekes/2019 // Public Domain
+# kubectl-sh-secret (part of ossobv/vcutil) // wdoekes/2019,2024
+#   // Public Domain
 #
 # Helper script to manage opaque secrets. Usage through kubectl wrapper.
 #
@@ -13,28 +14,30 @@
 #
 # That last version will enable tab-completion to work as usual.
 #
+set -eu
 test -z "${BASH_VERSION}" && echo "$0: requires bash" >&2 && exit 1
 
 # Reorder arguments:
 options=$(getopt -o n: -- "$@") || exit 1
 eval set -- "$options"
 while true; do
-    case "$1" in
+    case "${1:-}" in
     -n) shift; namespace="$1";;
     --) shift; break;;
+    *) echo "$0: programming error? $1" >&2; exit 1
     esac
     shift
 done
 
 # These arguments are needed for the kubectl-wrapper style to function:
-arg_get="$1"    # get
-arg_secret="$2" # secret[s]
+arg_get="$1"        # get
+arg_secret="${2:-}" # secret[s]
 
 # The actual arguments:
-secret="$3"     # [SECRET]
-key=$(echo "$4" | sed -e 's/[^A-Za-z0-9_.-]//')  # [KEY]
+secret="${3:-}"     # [SECRET]
+key=$(echo "${4:-}" | sed -e 's/[^A-Za-z0-9_.-]//')  # [KEY]
 key_esc=$(echo "$key" | sed -e 's/[.]/[.]/g')  # escape allowed magic tokens
-write="$5"      # [write]
+write="${5:-}"      # [write]
 
 if [[ $# -gt 5 ]] || [[ "$arg_get" != "get" ]] ||
         [[ "$arg_secret" != secret* ]] || (
