tcpdump247: Better handling of missing/moved tcpdump binary

diff --git a/tcpdump247 b/tcpdump247
--- a/tcpdump247
+++ b/tcpdump247
@@ -1,5 +1,5 @@
 #!/bin/bash
-# tcpdump247 (part of ossobv/vcutil) // wdoekes/2013-2016 // Public Domain
+# tcpdump247 (part of ossobv/vcutil) // wdoekes/2013-2016,2023 // Public Domain
 #
 # Script to start a rotating tcpdump. Restarts tcpdump if it dies.
 #
@@ -42,7 +42,7 @@
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 NAME=tcpdump247
 DESC="rotating traffic dumps wrapper"
-TCPDUMP=/usr/sbin/tcpdump
+TCPDUMP=$(command -v tcpdump)
 PIDFILE=/var/run/tcpdump247.pgid  # it's a pgid-file actually
 
 . /lib/lsb/init-functions
@@ -51,7 +51,10 @@ PIDFILE=/var/run/tcpdump247.pgid  # it's a pgid-file actually
 test -r /etc/default/tcpdump247 && . /etc/default/tcpdump247
 # sanity checks
 test "$ENABLED" != "1" && exit 0    # not enabled? (or exit 6?)
-test -x "$TCPDUMP" || exit 5        # no tcpdump found?
+if ! test -x "$TCPDUMP"; then
+    echo "tcpdump247: tcpdump bin not found or not executable" >&2
+    exit 5
+fi
 
 
 start_scripts() {
